version: '1'

services:
  postgres:
    image: postgres
    container_name: "murcydb"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres

  jblogger:
    build: .
    container_name: murcy
    ports:
      - "9090:8080"
      - "9797:8787"
    depends_on:
      - postgres